print("__#Soma de Fracao#__")
deno1=int(input("Digite o denominador "))
nume1=int(input("Digite o numerador "))
print ("Fracao #1 %d/%d"%(deno1,nume1))
deno2=int(input("Digite o denominador "))
nume2=int(input("Digite o numerador "))
print ("Fracao #1 %d/%d"%(deno1,nume1))
soma_deno = (deno1+deno2)
soma_nume=(nume1+nume2)
print ("%d/%d"%(soma_deno,soma_nume))
